services:
  app:
    build:
      context: ./formFeedback
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=start
      - DB_NAME=FeedBack
    volumes:
      - ./formFeedback:/app
      - /app/node_modules
    networks:
      - my_network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=start
      - MYSQL_DATABASE=FeedBack
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pstart"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - my_network

volumes:
  mysql-data:
networks:
  my_network:
    driver: bridge